// <auto-generated />
using System;
using FastCartMarketPlace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastCartMarketPlace.Migrations
{
    [DbContext(typeof(FastCartContext))]
    [Migration("20260515022148_SeedTwentyFiveProducts")]
    partial class SeedTwentyFiveProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FastCartMarketPlace.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Electronics",
                            Description = "A responsive mechanical keyboard for gaming, coding, and productivity.",
                            ImageURL = "keyboard.jpg",
                            Name = "Velocity Pro Keyboard",
                            Price = 89.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Audio",
                            Description = "Wireless noise-canceling headphones with clear audio quality.",
                            ImageURL = "headphones.jpg",
                            Name = "NovaSound Headphones",
                            Price = 129.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Furniture",
                            Description = "An ergonomic chair built for comfort during long sessions.",
                            ImageURL = "chair.jpg",
                            Name = "TitanX Office Chair",
                            Price = 199.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Wearables",
                            Description = "A smartwatch for tracking activity, heart rate, and notifications.",
                            ImageURL = "smartwatch.jpg",
                            Name = "PulseFit Smartwatch",
                            Price = 149.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductID = 5,
                            Category = "Electronics",
                            Description = "Portable battery pack with fast charging for mobile devices.",
                            ImageURL = "powerbank.jpg",
                            Name = "AeroCharge Power Bank",
                            Price = 39.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductID = 6,
                            Category = "Home Office",
                            Description = "LED desk lamp with adjustable brightness settings.",
                            ImageURL = "lamp.jpg",
                            Name = "EmberGlow Desk Lamp",
                            Price = 34.99m,
                            StockQuantity = 22
                        },
                        new
                        {
                            ProductID = 7,
                            Category = "Computers",
                            Description = "Compact desktop computer for school, work, and streaming.",
                            ImageURL = "minipc.jpg",
                            Name = "FrostByte Mini PC",
                            Price = 449.99m,
                            StockQuantity = 8
                        },
                        new
                        {
                            ProductID = 8,
                            Category = "Accessories",
                            Description = "Adjustable stand for tablets and small laptops.",
                            ImageURL = "tabletstand.jpg",
                            Name = "Horizon Tablet Stand",
                            Price = 24.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            ProductID = 9,
                            Category = "Electronics",
                            Description = "Comfortable wireless mouse with long battery life.",
                            ImageURL = "mouse.jpg",
                            Name = "Quantum Wireless Mouse",
                            Price = 29.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductID = 10,
                            Category = "Electronics",
                            Description = "HD webcam for meetings, classes, and streaming.",
                            ImageURL = "webcam.jpg",
                            Name = "ClearView Webcam",
                            Price = 59.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductID = 11,
                            Category = "Bags",
                            Description = "Durable backpack with padded laptop storage.",
                            ImageURL = "backpack.jpg",
                            Name = "Summit Laptop Backpack",
                            Price = 54.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductID = 12,
                            Category = "Audio",
                            Description = "USB microphone for podcasts, meetings, and gaming.",
                            ImageURL = "microphone.jpg",
                            Name = "StreamDeck Microphone",
                            Price = 79.99m,
                            StockQuantity = 16
                        },
                        new
                        {
                            ProductID = 13,
                            Category = "Home Office",
                            Description = "Adjustable monitor arm for better desk organization.",
                            ImageURL = "monitorarm.jpg",
                            Name = "CoreFlex Monitor Arm",
                            Price = 69.99m,
                            StockQuantity = 14
                        },
                        new
                        {
                            ProductID = 14,
                            Category = "Accessories",
                            Description = "Large desk mat for keyboards, mice, and workspaces.",
                            ImageURL = "deskmat.jpg",
                            Name = "GlidePad Desk Mat",
                            Price = 19.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            ProductID = 15,
                            Category = "Accessories",
                            Description = "Charging cable set for phones, tablets, and accessories.",
                            ImageURL = "cables.jpg",
                            Name = "SparkCharge Cable Kit",
                            Price = 17.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            ProductID = 16,
                            Category = "Audio",
                            Description = "Compact earbuds with charging case and clear sound.",
                            ImageURL = "earbuds.jpg",
                            Name = "EchoBuds Wireless Earbuds",
                            Price = 64.99m,
                            StockQuantity = 28
                        },
                        new
                        {
                            ProductID = 17,
                            Category = "Stationery",
                            Description = "Simple productivity planner for school and work tasks.",
                            ImageURL = "planner.jpg",
                            Name = "BrightNote Planner",
                            Price = 12.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            ProductID = 18,
                            Category = "Computers",
                            Description = "Cooling pad that helps laptops stay at safer temperatures.",
                            ImageURL = "coolingpad.jpg",
                            Name = "Orbit Laptop Cooling Pad",
                            Price = 31.99m,
                            StockQuantity = 26
                        },
                        new
                        {
                            ProductID = 19,
                            Category = "Lifestyle",
                            Description = "Insulated bottle that keeps drinks cold or hot.",
                            ImageURL = "bottle.jpg",
                            Name = "Metro Stainless Bottle",
                            Price = 22.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            ProductID = 20,
                            Category = "Lifestyle",
                            Description = "Glasses designed to reduce eye strain during screen time.",
                            ImageURL = "glasses.jpg",
                            Name = "FocusGuard Blue Light Glasses",
                            Price = 18.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductID = 21,
                            Category = "Home Office",
                            Description = "Comfortable foot rest for improved posture at a desk.",
                            ImageURL = "footrest.jpg",
                            Name = "ZenDesk Foot Rest",
                            Price = 27.99m,
                            StockQuantity = 19
                        },
                        new
                        {
                            ProductID = 22,
                            Category = "Accessories",
                            Description = "Multi-port USB hub for laptops and desktops.",
                            ImageURL = "usbhub.jpg",
                            Name = "RapidLink USB Hub",
                            Price = 25.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductID = 23,
                            Category = "Computers",
                            Description = "24-inch monitor for work, school, and entertainment.",
                            ImageURL = "monitor.jpg",
                            Name = "PrimeView 24 Monitor",
                            Price = 159.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            ProductID = 24,
                            Category = "Home",
                            Description = "Soft blanket for home, office, or dorm use.",
                            ImageURL = "blanket.jpg",
                            Name = "CloudSoft Throw Blanket",
                            Price = 29.99m,
                            StockQuantity = 32
                        },
                        new
                        {
                            ProductID = 25,
                            Category = "Accessories",
                            Description = "Adjustable phone mount for desks and video calls.",
                            ImageURL = "phonestand.jpg",
                            Name = "SnapStand Phone Mount",
                            Price = 15.99m,
                            StockQuantity = 70
                        });
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            Comment = "Excellent keyboard. The keys feel smooth and responsive.",
                            CustomerName = "Alex Morgan",
                            ProductID = 1,
                            Rating = 5
                        },
                        new
                        {
                            ReviewID = 2,
                            Comment = "Great for gaming and schoolwork. Very solid build quality.",
                            CustomerName = "Jamie Carter",
                            ProductID = 1,
                            Rating = 4
                        },
                        new
                        {
                            ReviewID = 3,
                            Comment = "The sound quality is impressive and the battery lasts a long time.",
                            CustomerName = "Taylor Brooks",
                            ProductID = 2,
                            Rating = 5
                        },
                        new
                        {
                            ReviewID = 4,
                            Comment = "Comfortable chair and easy to assemble.",
                            CustomerName = "Jordan Lee",
                            ProductID = 3,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.OrderItem", b =>
                {
                    b.HasOne("FastCartMarketPlace.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastCartMarketPlace.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Review", b =>
                {
                    b.HasOne("FastCartMarketPlace.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
