// <auto-generated />
using System;
using FastCartMarketPlace.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastCartMarketPlace.Migrations
{
    [DbContext(typeof(FastCartContext))]
    [Migration("20260515011545_SeedProductsAndReviews")]
    partial class SeedProductsAndReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("FastCartMarketPlace.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Category = "Electronics",
                            Description = "A responsive mechanical keyboard designed for gaming, coding, and everyday productivity.",
                            ImageURL = "keyboard.jpg",
                            Name = "Velocity Pro Keyboard",
                            Price = 89.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductID = 2,
                            Category = "Audio",
                            Description = "Wireless noise-canceling headphones with long battery life and clear audio quality.",
                            ImageURL = "headphones.jpg",
                            Name = "NovaSound Headphones",
                            Price = 129.99m,
                            StockQuantity = 18
                        },
                        new
                        {
                            ProductID = 3,
                            Category = "Furniture",
                            Description = "An ergonomic office chair built for comfort during long work or gaming sessions.",
                            ImageURL = "chair.jpg",
                            Name = "TitanX Office Chair",
                            Price = 199.99m,
                            StockQuantity = 12
                        },
                        new
                        {
                            ProductID = 4,
                            Category = "Wearables",
                            Description = "A smartwatch that tracks steps, heart rate, notifications, and daily activity goals.",
                            ImageURL = "smartwatch.jpg",
                            Name = "PulseFit Smartwatch",
                            Price = 149.99m,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Review", b =>
                {
                    b.Property<int>("ReviewID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewID");

                    b.HasIndex("ProductID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewID = 1,
                            Comment = "Excellent keyboard. The keys feel smooth and responsive.",
                            CustomerName = "Alex Morgan",
                            ProductID = 1,
                            Rating = 5
                        },
                        new
                        {
                            ReviewID = 2,
                            Comment = "Great for gaming and schoolwork. Very solid build quality.",
                            CustomerName = "Jamie Carter",
                            ProductID = 1,
                            Rating = 4
                        },
                        new
                        {
                            ReviewID = 3,
                            Comment = "The sound quality is impressive and the battery lasts a long time.",
                            CustomerName = "Taylor Brooks",
                            ProductID = 2,
                            Rating = 5
                        },
                        new
                        {
                            ReviewID = 4,
                            Comment = "Comfortable chair and easy to assemble.",
                            CustomerName = "Jordan Lee",
                            ProductID = 3,
                            Rating = 4
                        });
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.OrderItem", b =>
                {
                    b.HasOne("FastCartMarketPlace.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastCartMarketPlace.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Review", b =>
                {
                    b.HasOne("FastCartMarketPlace.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FastCartMarketPlace.Models.Product", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
